Set-WindowsExplorerOptions -EnableShowHiddenFilesFoldersDrives -EnableShowProtectedOSFiles -EnableShowFileExtensions
Set-TaskbarOptions -Size Large -Lock -Combine Never
cinst git
cinst nodejs
cinst sysinternals
cinst notepad2
cinst fiddler
cinst wireshark
cinst burp-suite-free-edition
cinst firefox
cinst googlechrome
cinst paint.net
cinst 7zip
cinst kdiff3
cinst ffmpeg
cinst youtube-dl 
cinst vlc
cinst visualstudiocode
cinst visualstudio2017community
cinst visualstudio2017-workload-azure
cinst visualstudio2017-workload-netcoretools
cinst visualstudio2017-workload-netweb
cinst visualstudio2017-workload-node
cinst chocolatey
cinst virtualbox
cinst audacity
cinst postman
cinst anaconda3
cinst qbittorrent
