Set-WindowsExplorerOptions -EnableShowHiddenFilesFoldersDrives -EnableShowProtectedOSFiles -EnableShowFileExtensions
Set-TaskbarOptions -Size Large -Lock -Combine Never
cinst git
cinst nodejs
cinst sysinternals
cinst notepad2
cinst fiddler
cinst wireshark
cinst burp-suite-free-edition
cinst firefox
cinst googlechrome
cinst paint.net
cinst 7zip
cinst kdiff3
cinst ffmpeg
cinst youtube-dl 
cinst vlc
cinst visualstudiocode
cinst visualstudio2019community
cinst visualstudio2019-workload-azure
cinst visualstudio2019-workload-netcoretools
cinst visualstudio2019-workload-netweb
cinst chocolatey
cinst virtualbox
cinst audacity
cinst audacity-lame
cinst postman
cinst anaconda3
cinst qbittorrent
cinst handbrake
cinst sql-server-management-studio
cinst windirstat
